### ISSUE TITLE
出现Package fontspec Warning: Font "FandolSong-Regular" does not contain requested Script "CJK".的警告

### ISSUE THREAD

**Issue by Rectifierr** [XayahSuSuSu/Latex-HNUThesisTemplate#1]
出现Package fontspec Warning: Font "FandolSong-Regular" does not contain requested Script "CJK".的警告且公式中的英文字体不为Times new Roman，在序言加上fontset=windows仍然出现该警告

**Comment by Rectifierr** [comment]
![Uploading Snipaste_2024-05-07_17-06-17.png…]()

**Comment by XayahSuSuSu** [comment]
1. 你是Mac系统吗，我这边Windows下测试没有这个警告，并且在Win和Linux上编译产出的pdf字体也都是正常的，如果你那边产出的pdf字体是正常的话可以暂时忽略这个警告
2. 规范文件里关于公式的描述并没有提到公式字体要求，所以模板使用的是公式默认的字体，如果你想在公式中使用Times New Roman字体，可以在`main.tex`中加入
```
\usepackage{mathptmx}
```

**Comment by Rectifierr** [comment]
谢谢回复！
关于1：pdf输出是正常的，最后我在main.tex中添加了一行：\PassOptionsToPackage{quiet}{fontspec}消除了该警告。
关于2：导入mathptmx宏包后公式的字体变成了Times New Roman，但正文中的英文在导入这个包后又变得不是Times New Roman字体了。根据https://www.latexstudio.net/archives/9323.html中的内容，我添加了fontenc宏包，最后正文和公式中的英文均变成了Times New Roman字体。
我的问题已经全部解决，再次感谢你的回复！

**Comment by Rectifierr** [comment]
谢谢回复！
关于1：pdf输出是正常的，最后我在main.tex中添加了一行：\PassOptionsToPackage{quiet}{fontspec}消除了该警告。
关于2：导入mathptmx宏包后公式的字体变成了Times New Roman，但正文中的英文在导入这个包后又变得不是Times New Roman字体了。根据(https://www.latexstudio.net/archives/9323.html)中的内容，我添加了fontenc宏包，最后正文和公式中的英文均变成了Times New Roman字体。
我的问题已经全部解决，再次感谢你的回复！

**Comment by Rectifierr** [comment]
谢谢回复！
关于1：pdf输出是正常的，最后我在main.tex中添加了一行：\PassOptionsToPackage{quiet}{fontspec}消除了该警告。
关于2：导入mathptmx宏包后公式的字体变成了Times New Roman，但正文中的英文在导入这个包后又变得不是Times New Roman字体了。根据([latexstudio](https://www.latexstudio.net/archives/9323.html)中的内容增加了fontenc 宏包解决了这个问题。
我的问题已经全部解决，再次感谢你的回复！

**Comment by Rectifierr** [comment]
谢谢回复！
关于1：pdf输出是正常的，最后我在main.tex中添加了一行：\PassOptionsToPackage{quiet}{fontspec}消除了该警告。
关于2：导入mathptmx宏包后公式的字体变成了Times New Roman，但正文中的英文在导入这个包后又变得不是Times New Roman字体了。根据[latexstudio](https://www.latexstudio.net/archives/9323.html)中的内容增加了fontenc 宏包解决了这个问题。

该字体问题已经解决，再次感谢回复！
