### ISSUE TITLE
说明中两行标题的修改提示疑似有误

### ISSUE THREAD

**Issue by Rectifierr** [XayahSuSuSu/Latex-HNUThesisTemplate#2]
按说明中的修改会出现第二行没有横线的情况，好像少打了一行
可以修改为：
`\begin{tabular}{r l}
    {\sizeTwol {
        \fontSimheiBold 论文\fontTimesNewRoman \hspace{0pt} (\fontSimheiBold 设计\fontTimesNewRoman )\hspace{0pt}\fontSimheiBold 题目：
    }} & {\sizeThreel {
        \fontSimsun\fontTimesNewRoman\underline{\makebox[\contentLenght][c]{
            你说得对但是原神是一款 
        }}
    }} \\
     \specialrule{0em}{\contentVerticalSpace}{0pt}
    {\sizeFour {
        \fontSimhei
    }} & {\sizeThreel {
        \fontSimsun\fontTimesNewRoman\underline{\makebox[\contentLenght][c]{
             自主研发的开放世界游戏
        }}
    }}  \\`
就能显示两行标题了

**Comment by XayahSuSuSu** [comment]
按理说应该有的吧，这边测试是正常的
![image](https://github.com/XayahSuSuSu/Latex-HNUThesisTemplate/assets/44322170/8535b8c8-1c38-4af9-9b57-0335a6839c8e)
![image](https://github.com/XayahSuSuSu/Latex-HNUThesisTemplate/assets/44322170/4c5ccea5-4635-4f76-8ac7-86b626b0c567)
